### ISSUE TITLE
2dvectors - magnitude placeholder incorrect

### ISSUE THREAD

**Issue by zekemccrary** [quintindunn/APhysicsWeb#15]
In the 2dvectors branch when the JavaScript clears the table it doesn't use the correct placeholder text in the magnitude column.
<img width="602" alt="Screenshot 2023-09-18 at 22 14 01" src="https://github.com/quintindunn/APhysicsWeb/assets/145229456/bb1c72f1-09bc-4035-aeb0-53c14ee568ed">
-->
<img width="599" alt="Screenshot 2023-09-18 at 22 14 17" src="https://github.com/quintindunn/APhysicsWeb/assets/145229456/65d2b288-a1e2-43d5-a798-71a86cb03056">

**Comment by quintindunn** [comment]
Resolved, now at the top of the `vector_addition_calculator.js` there is a constant for translations that will be used, easier for future if we ever want to support other languages.
