### ISSUE TITLE
[Bug]- Hide output box on 2D Vector calculator when no content is displayed.

### ISSUE THREAD

**Issue by quintindunn** [quintindunn/APhysicsWeb#21]
The output div is shown as an empty div with a border when there's no calculations / values displayed. It should be hidden if there's no values found.
<img width="1357" alt="Screenshot 2023-09-19 at 10 59 38 AM" src="https://github.com/quintindunn/APhysicsWeb/assets/93884113/6c6780cd-5fa8-4269-96fd-05dbf3da7926">

**Comment by zekemccrary** [comment]
In progress

**Comment by quintindunn** [comment]
Gone!

**Comment by quintindunn** [comment]
Very not gone!

**Comment by quintindunn** [comment]
Actually gone now in commit 06334584fede037bf9318b22c933372b6efe4d3a
